Feature/about
JoabsonDev/essentials-v2 pull request #6
Opened 2024-09-04 16:16 UTC by ThiagoArebalo

Favor verificar se está dentro do especificado.

2024-09-04 17:13 UTC, JoabsonDev requested changes

2024-09-04 17:13 UTC, JoabsonDev commented on index.html
> +            <i class="fa-solid fa-chart-line"></i>
Os icones desse trecho devem pertencer ao seu grupo de informações respectivo

2024-09-04 17:13 UTC, JoabsonDev commented on css/layout/about/chart.css
> +.chart__description p {
Nos estilos anteriores você usou .l-chart, .l-chart i, .l-chart img etc.
Nessa linha você quebrou o padrão ".chart__description p" era pra ser ".l-chart__description p"

2024-09-04 17:13 UTC, JoabsonDev commented on css/layout/about/chart.css
> +.chart__icons {
Faltou o padrão do namespace ".l-"

2024-09-04 17:13 UTC, JoabsonDev commented on css/layout/about/chart.css
> +.chart__info {
Faltou o padrão do namespace ".l-"

2024-09-04 17:13 UTC, JoabsonDev commented on css/layout/about/chart.css
> +.chart__description {
Faltou o padrão do namespace ".l-"

2024-09-04 22:19 UTC, JoabsonDev requested changes

2024-09-04 22:19 UTC, JoabsonDev commented on css/layout/about/chart.css
> +  /* gap: 0.75rem; */
Remover comentários não necessários do código

2024-09-04 22:19 UTC, JoabsonDev commented on index.html
> +        <article class="l-chart l-box l-box.l-box--border">
.l-box--border não se usa no HTML e sim no css

2024-09-12 01:05 UTC, ThiagoArebalo commented on css/layout/about/chart.css
> +  /* gap: 0.75rem; */
Remover essas linhas irá tirar do padrão a parte citada.

2024-09-12 01:06 UTC, ThiagoArebalo commented on index.html
> +        <article class="l-chart l-box l-box.l-box--border">
Corrigido!

2024-09-12 01:10 UTC, ThiagoArebalo commented on index.html
> +            <i class="fa-solid fa-chart-line"></i>
corrigido!

2024-09-12 01:10 UTC, ThiagoArebalo commented on css/layout/about/chart.css
> +.chart__description p {
corrigido!

2024-09-12 01:11 UTC, ThiagoArebalo commented on css/layout/about/chart.css
> +.chart__icons {
corrigido!

2024-09-12 01:11 UTC, ThiagoArebalo commented on css/layout/about/chart.css
> +.chart__info {
corrigido!

2024-09-12 01:11 UTC, ThiagoArebalo commented on css/layout/about/chart.css
> +.chart__description {
corrigido!

2024-09-16 19:24 UTC, JoabsonDev requested changes

2024-09-16 19:24 UTC, JoabsonDev commented on css/layout/about/chart.css
> +  align-items: center;
align-items só funciona se tiver um display como flex. No caso, você colocou um display: block

2024-09-16 19:24 UTC, JoabsonDev commented on css/layout/about/chart.css
> +  flex-direction: row;
flex-direction: row; por padrão já é row... é necessário mesmo adicionar esse estilo?

2024-09-16 19:24 UTC, JoabsonDev commented on css/layout/about/chart.css
> +  width: 540px;
Estamos com problema de responsividade. Essa propriedade não pode ser fixa

2024-09-16 19:24 UTC, JoabsonDev commented on css/layout/about/chart.css
> +  width: 510px;
Esse valor deve ser fixo mesmo?

2024-09-16 19:24 UTC, JoabsonDev commented on css/layout/about/video.css
> +  font-weight: 400;
Se não me engano, peso 400 já é o padrão. Será necessário colocar essa propriedade css?

2024-09-16 19:30 UTC, JoabsonDev requested changes

2024-09-16 19:30 UTC, JoabsonDev commented on index.html
> +        <article class="l-video">
Cadê o l-box?

2024-09-16 19:30 UTC, JoabsonDev commented on index.html
> +          <div class="l-video__content">
cadê o l-box__body?

2024-09-16 19:31 UTC, JoabsonDev requested changes

2024-09-16 19:31 UTC, JoabsonDev commented on index.html
> +          <div class="l-chart__info">
cadê o l-box__body?

2024-09-16 22:23 UTC, ThiagoArebalo commented on css/layout/about/chart.css
> +  align-items: center;
Corrigido.

2024-09-16 22:27 UTC, ThiagoArebalo commented on css/layout/about/chart.css
> +  flex-direction: row;
Nessa situação é necessário pois o eixo está alinhado na horizontal. Se colocar no padrão da propriedade, ficarão 1 elemento acima do outro, dessa forma não atendendo o padrão do original.

2024-09-17 00:07 UTC, ThiagoArebalo commented on css/layout/about/chart.css
> +  flex-direction: row;
> Nessa situação é necessário pois o eixo está alinhado na horizontal. Se colocar no padrão da propriedade, ficará 1 elemento acima do outro, dessa forma não atendendo o padrão do original. Quando for diminuir a resolução da tela, atendendo a responsivdade, será necessário criar um @media Quere para mudar o Flex-direction para "column" e o img irá para baixo das informações.

2024-09-17 00:11 UTC, ThiagoArebalo commented on css/layout/about/chart.css
> +  width: 540px;
corrigido.

2024-09-17 00:14 UTC, ThiagoArebalo commented on css/layout/about/chart.css
> +  width: 510px;
Não, foi alterado para max-width: 40%.

2024-09-17 00:15 UTC, ThiagoArebalo commented on css/layout/about/video.css
> +  font-weight: 400;
corrigido.

2024-09-17 00:16 UTC, ThiagoArebalo commented on index.html
> +        <article class="l-video">
corrigido.

2024-09-17 00:27 UTC, ThiagoArebalo commented on index.html
> +          <div class="l-video__content">
adicionado.

2024-09-17 00:32 UTC, ThiagoArebalo commented on index.html
> +          <div class="l-chart__info">
Essa propriedade não se adequa nesse local pois essa  _div_ está em row na configuração atual, após o @mediaQuere pode ser que se adeque.

2024-09-29 18:47 UTC, JoabsonDev approved these changes

2024-09-29 18:47 UTC, merged